### ISSUE TITLE
ngrok communication not working

### ISSUE THREAD

**Issue by hunterfrerich** [imperator-maximus/stable-diffusion-krita#13]
Using Krita 5.1.0 and sd_plugin_krita_beta32.zip (from today), I cannot get any confirmation messages to show in google colab, or any images returned in Krita.  

![krita_huAk8JkW3m](https://user-images.githubusercontent.com/15109673/189859701-c7a1652b-7fd3-44f9-9f83-75e412b3beff.png)

After selecting any method such as "from text" and hitting okay, I would expect to see something like
  
```  
txt2img
Batch 1 out of 2: 100% 15/15 [00:09<00:00,  1.66it/s]
Batch 2 out of 2: 100% 15/15 [00:04<00:00,  3.03it/s]
127.0.0.1 - - [12/Sep/2022 19:16:10] "POST /api/ HTTP/1.1" 200 -
```  
as shown in the [Krita Stable Diffusion (New API).ipynb](https://colab.research.google.com/drive/1eq-VF2dRHgxNjtPX5iZbDPuwtfJIEhtx#scrollTo=bYpxm4Fw2tLT).   
  
But I see no response, and no images are returned, even when I set the steps to very low, or try other setting options.  
  
I've confirmed that ckpt file was successfully copied to models/ldm/stable-diffusion-v1/model.ckpt

---  
  
To troubleshoot, I tried (in a separate colab notebook, during a separate attempt) using my own ngrok personal authtoken with the code (run after server start+stop):  
  
```
%cd /content
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz
!tar -xvf /content/ngrok-stable-linux-amd64.tgz
!./ngrok authtoken TOKENHERE
%cd /content/stable-diffusion/
```

This seemed to successfully pass the authtoken, because the ngrok html page loaded with a different message when you open in browser.   
  
That still did not work, and nothing changed.

---

Am I doing something wrong to use the program? I had to look at old twitter videos to even make sure there were no additional steps to start generation... but I don't know if something has changed, or if there is a particular way it must be started.

also, the discord link [on your website](https://www.flyingdog.de/sd/en/) has expired

**Comment by imperator-maximus** [comment]
hello, that solution might be pretty simple - have you tried to run Krita as admin?

**Comment by hunterfrerich** [comment]
> have you tried to run Krita as admin  
  
Thanks! It works now.  
   
Maybe that should be put more prominently in the documentation.

**Comment by imperator-maximus** [comment]
great! I wrote it on download page already. but better would be to just solve that issue :)  it is on my list to ask Krita folks about a solution here.
