### ISSUE TITLE
Plugin Fails to load on Ubuntu/Linux

### ISSUE THREAD

**Issue by LoopControl** [imperator-maximus/stable-diffusion-krita#2]
Thanks for creating this plugin.

Unfortunately on Linux, this plugin fails to load because the `from asyncio.windows_events import NULL` line in `stable_diffusion.py` throws a `win32 only` error.

**Comment by imperator-maximus** [comment]
this is fixed in next version (making last test now). This is same on Mac so I was already working on this. Thanks for detailed report!

**Comment by imperator-maximus** [comment]
fixed in Beta 2

**Comment by LoopControl** [comment]
Just confirming that beta2 does indeed work on Linux / Ubuntu. Thanks!
