### ISSUE TITLE
Error when img2img

### ISSUE THREAD

**Issue by Porkechebure** [imperator-maximus/stable-diffusion-krita#5]
Hello,
Text2img works
When i do img2img i get the following (NOTE image is 512x512 as specified)

> TypeError
> Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
> Wed Sep  7 15:06:59 2022
> 
> A problem occurred in a Python script.  Here is the sequence of
> function calls leading up to the error, in the order they occurred.
> 
>  C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py in ImageToImage()
>   708         p.strength=data["strength"]
>   709         images = runSD(p)
>   710         imageResultDialog( images,p)
>   711 
>   712 
> global imageResultDialog = <function imageResultDialog>
> images = None
> p = <stable_diffusion_krita.sd_main.SDParameters object>
> 
>  C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py in imageResultDialog(qImgs=None, p=<stable_diffusion_krita.sd_main.SDParameters object>)
>   510 
>   511 def imageResultDialog(qImgs,p):
>   512     dlg = showImages(qImgs,p)
>   513     if dlg.exec():
>   514         print("HQ Update here")
> dlg undefined
> global showImages = <class 'stable_diffusion_krita.sd_main.showImages'>
> qImgs = None
> p = <stable_diffusion_krita.sd_main.SDParameters object>
> 
>  C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py in __init__(self=<stable_diffusion_krita.sd_main.showImages object>, qImgs=None, p=<stable_diffusion_krita.sd_main.SDParameters object>)
>   429         self.qImgs=qImgs
>   430         i=0
>   431         for qImg in qImgs:
>   432             v_layout = QVBoxLayout()
>   433             layout.addLayout(v_layout)
> qImg undefined
> qImgs = None
> TypeError: 'NoneType' object is not iterable
>     __cause__ = None
>     __class__ = <class 'TypeError'>
>     __context__ = None
>     __delattr__ = <method-wrapper '__delattr__' of TypeError object>
>     __dict__ = {}
>     __dir__ = <built-in method __dir__ of TypeError object>
>     __doc__ = 'Inappropriate argument type.'
>     __eq__ = <method-wrapper '__eq__' of TypeError object>
>     __format__ = <built-in method __format__ of TypeError object>
>     __ge__ = <method-wrapper '__ge__' of TypeError object>
>     __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
>     __gt__ = <method-wrapper '__gt__' of TypeError object>
>     __hash__ = <method-wrapper '__hash__' of TypeError object>
>     __init__ = <method-wrapper '__init__' of TypeError object>
>     __init_subclass__ = <built-in method __init_subclass__ of type object>
>     __le__ = <method-wrapper '__le__' of TypeError object>
>     __lt__ = <method-wrapper '__lt__' of TypeError object>
>     __ne__ = <method-wrapper '__ne__' of TypeError object>
>     __new__ = <built-in method __new__ of type object>
>     __reduce__ = <built-in method __reduce__ of TypeError object>
>     __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
>     __repr__ = <method-wrapper '__repr__' of TypeError object>
>     __setattr__ = <method-wrapper '__setattr__' of TypeError object>
>     __setstate__ = <built-in method __setstate__ of TypeError object>
>     __sizeof__ = <built-in method __sizeof__ of TypeError object>
>     __str__ = <method-wrapper '__str__' of TypeError object>
>     __subclasshook__ = <built-in method __subclasshook__ of type object>
>     __suppress_context__ = False
>     __traceback__ = <traceback object>
>     args = ("'NoneType' object is not iterable",)
>     with_traceback = <built-in method with_traceback of TypeError object>
> 
> The above is a description of an error in a Python program.  Here is
> the original traceback:
> 
> Traceback (most recent call last):
>   File "C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 710, in ImageToImage
>     imageResultDialog( images,p)
>   File "C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 512, in imageResultDialog
>     dlg = showImages(qImgs,p)
>   File "C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 431, in __init__
>     for qImg in qImgs:
> TypeError: 'NoneType' object is not iterable

The server error popup:

> Endpoint: http://localhost:7860/api/predict/, Reason: Traceback (most recent call last):
>   File "C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 536, in getServerData
>     with urllib.request.urlopen(req) as f:
>   File "urllib\request.py", line 222, in urlopen
>   File "urllib\request.py", line 531, in open
>   File "urllib\request.py", line 640, in http_response
>   File "urllib\request.py", line 569, in error
>   File "urllib\request.py", line 502, in _call_chain
>   File "urllib\request.py", line 649, in http_error_default
> urllib.error.HTTPError: HTTP Error 500: Internal Server Error

![image](https://user-images.githubusercontent.com/3466040/188888027-678216c8-b5fb-4aed-a6d4-06d3799dd5bd.png)

Screenshot for more clarity
![image](https://user-images.githubusercontent.com/3466040/188887126-31181c4e-5912-4762-8aa7-9381723d70da.png)

![image](https://user-images.githubusercontent.com/3466040/188887279-386685b3-db33-4bb8-9993-cc8b0e0fc61d.png)

Also inpainting does it:

> TypeError
> Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
> Wed Sep  7 15:16:34 2022
> 
> A problem occurred in a Python script.  Here is the sequence of
> function calls leading up to the error, in the order they occurred.
> 
>  C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py in Inpainting()
>   774         p.maskImage64=maskImage64
>   775         images = runSD(p)
>   776         imageResultDialog( images,p)
>   777 
>   778 # config dialog
> global imageResultDialog = <function imageResultDialog>
> images = None
> p = <stable_diffusion_krita.sd_main.SDParameters object>
> 
>  C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py in imageResultDialog(qImgs=None, p=<stable_diffusion_krita.sd_main.SDParameters object>)
>   510 
>   511 def imageResultDialog(qImgs,p):
>   512     dlg = showImages(qImgs,p)
>   513     if dlg.exec():
>   514         print("HQ Update here")
> dlg undefined
> global showImages = <class 'stable_diffusion_krita.sd_main.showImages'>
> qImgs = None
> p = <stable_diffusion_krita.sd_main.SDParameters object>
> 
>  C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py in __init__(self=<stable_diffusion_krita.sd_main.showImages object>, qImgs=None, p=<stable_diffusion_krita.sd_main.SDParameters object>)
>   429         self.qImgs=qImgs
>   430         i=0
>   431         for qImg in qImgs:
>   432             v_layout = QVBoxLayout()
>   433             layout.addLayout(v_layout)
> qImg undefined
> qImgs = None
> TypeError: 'NoneType' object is not iterable
>     __cause__ = None
>     __class__ = <class 'TypeError'>
>     __context__ = None
>     __delattr__ = <method-wrapper '__delattr__' of TypeError object>
>     __dict__ = {}
>     __dir__ = <built-in method __dir__ of TypeError object>
>     __doc__ = 'Inappropriate argument type.'
>     __eq__ = <method-wrapper '__eq__' of TypeError object>
>     __format__ = <built-in method __format__ of TypeError object>
>     __ge__ = <method-wrapper '__ge__' of TypeError object>
>     __getattribute__ = <method-wrapper '__getattribute__' of TypeError object>
>     __gt__ = <method-wrapper '__gt__' of TypeError object>
>     __hash__ = <method-wrapper '__hash__' of TypeError object>
>     __init__ = <method-wrapper '__init__' of TypeError object>
>     __init_subclass__ = <built-in method __init_subclass__ of type object>
>     __le__ = <method-wrapper '__le__' of TypeError object>
>     __lt__ = <method-wrapper '__lt__' of TypeError object>
>     __ne__ = <method-wrapper '__ne__' of TypeError object>
>     __new__ = <built-in method __new__ of type object>
>     __reduce__ = <built-in method __reduce__ of TypeError object>
>     __reduce_ex__ = <built-in method __reduce_ex__ of TypeError object>
>     __repr__ = <method-wrapper '__repr__' of TypeError object>
>     __setattr__ = <method-wrapper '__setattr__' of TypeError object>
>     __setstate__ = <built-in method __setstate__ of TypeError object>
>     __sizeof__ = <built-in method __sizeof__ of TypeError object>
>     __str__ = <method-wrapper '__str__' of TypeError object>
>     __subclasshook__ = <built-in method __subclasshook__ of type object>
>     __suppress_context__ = False
>     __traceback__ = <traceback object>
>     args = ("'NoneType' object is not iterable",)
>     with_traceback = <built-in method with_traceback of TypeError object>
> 
> The above is a description of an error in a Python program.  Here is
> the original traceback:
> 
> Traceback (most recent call last):
>   File "C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 776, in Inpainting
>     imageResultDialog( images,p)
>   File "C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 512, in imageResultDialog
>     dlg = showImages(qImgs,p)
>   File "C:\Users\Shadow\AppData\Roaming\krita\pykrita\stable_diffusion_krita\sd_main.py", line 431, in __init__
>     for qImg in qImgs:
> TypeError: 'NoneType' object is not iterable
> 
>

**Comment by imperator-maximus** [comment]
Please use Beta 3, communication has beeen rewritten, so these kind of errors are fixed now. see https://www.flyingdog.de/sd/en/
