### ISSUE TITLE
The webservice URL does not save

### ISSUE THREAD

**Issue by i2chris** [imperator-maximus/stable-diffusion-krita#8]
![Screenshot from 2022-09-08 09-45-35](https://user-images.githubusercontent.com/35810281/189080098-4c878670-f3c3-459e-8ead-3be259d936a4.png)
Hi

I have two issues here and they might be related.

In the plugin settings, when I set the URL to the location of my network computer running the API, it does not remember it when I close and re-open Krita.  I have to set it each time.

This is what I'm doing:

1. Open Stable Diffussion settings in Krita, set the URL to "http://192.168.86.48:5000", Click "OK", 
2. Restart Krita
3. Open settings, the URL goes back to http://localhost:7860

The other (related?) issue is that after I set the URL, none of the functionality works and it does not connect to my remote machine at http://192.168.86.48:5000.  

I have tried running "From Text" and "From Image", but nothing appears in the server logs on the API. Nothing is getting through.

I am running the correct fork and I have opened the API to the network on 0.0.0.0 (see screenshot) and I can access the URL http://192.168.86.48:5000 via my local browser, so the Firewall etc is not the issue here.  

Perhaps the updated URL is just not being used at all because it can't save it?

Operating System: Ubuntu 20.04,  running as an AppImage.  Maybe this is an AppImage issue?

Thanks

Chris

**Comment by imperator-maximus** [comment]
Hello, 
thanks for Feedback.
several Windows user also had that problem and solution was to run Krita as Admin. For you I think it is similar problem but I think with AppImage this might not solve this here but you can try.
the path is coming from Krita API 
rPath= Krita.instance().readSetting("","ResourceDirectory","")
I will check out if there are alternatives later.

**Comment by imperator-maximus** [comment]
ah it seems that this one fixes it already: https://github.com/imperator-maximus/stable-diffusion-krita/pull/4
I had no time yeserday to check that out because of the old API issues.

**Comment by i2chris** [comment]
Yes. I can confirm this works 

Thanks :-)
