### ISSUE TITLE
[feature] Denoising strength for Inpainting

### ISSUE THREAD

**Issue by jpbrodsky** [imperator-maximus/stable-diffusion-krita#9]
It would be very useful to add a denoising strength selector for inpainting. This allows the inpainting process to better consider the content of the original image when using the "original" inpaint fill selection.

Looki on the discord offered this patch that covers adding the slider, though line numbers may need changing with the newest version.

https://pastebin.com/raw/tCP7ESnk

**Comment by imperator-maximus** [comment]
integrated in new version - thank you
